### PR TITLE
#710 Remove context() from the top of each test file.

### PR DESCRIPTION
**Pull request by bms63**

### CODE REVIEW

**Review by thomas-neitmann — APPROVED** [review]
Thanks a lot!

**Comment by bms63** [comment]
@thomas-neitmann I just realized this went into master :(

**Comment by thomas-neitmann** [comment]
Upps, I didn't realize that. I'll merge `master` into `devel`, then we have it there as well.

**Comment by bms63** [comment]
Okay to just delete this branch?  No need to revert or do anything else??

**Comment by thomas-neitmann** [comment]
Yes, just delete and we're fine :)

I already merged `master` into `devel`.

**Pull request merged**
