### PR TITLE
722 derive param exposure

### PR DESCRIPTION
**Pull request by rossfarrugia**
#722 i updated the derive_params_exposure R program to rename to param instead of params and updated the examples, and i updated the corresponding unit test program with params->param. hope i didn't miss anything! at first i did this via RStudio and created new versions of the programs with the new name and pushed them here, but then realised i could do such minor updates way easier in GitHub directly so i deleted those new file commits and just updated and renamed the 2 "params" files directly.

### CODE REVIEW

**Review by bundfussr — CHANGES_REQUESTED** [review]
Thanks for your contribution.

Could you please
- link the issue to the pull request,
- deprecate the old function, i.e., `derive_params_exposure()` should still work but issue a warning, see the "Deprecation" section in the [Programming Strategy](https://roche-gsk.github.io/admiral/articles/programming_strategy.html#deprecation-1) for details and derive_var_base.R in the devel branch for an example, and 
- update the Changelog (NEWS.md)?

**Comment by rossfarrugia** [comment]
@bundfussr i think i've done all those pieces now - can you take another look please? thanks for all the tips!

**Review by bundfussr — CHANGES_REQUESTED** [review]
Please add
```
deprecate_warn("0.6.0", "derive_params_exposure()", "derive_param_exposure()")
```
as first line in `derive_params_exposure()`. This issues a warning if the function is called.

Could you also move line 54/55
```
#'   *Permitted Values:* List of variable-value pairs` to line
#'
```
to line 50? It is not related to the issue. Just a typo we did not notice before.

**Comment by rossfarrugia** [comment]
got it @bundfussr - now updated

**Review by bundfussr — CHANGES_REQUESTED** [review]
Thanks, could you rerun `devtools::document()` and add the updated files in man/?

**Comment by rossfarrugia** [comment]
@bundfussr yes sorry missed that, now done.

**Review by bundfussr — APPROVED** [review]

**Comment by thomas-neitmann** [comment]
Thanks a lot @rossfarrugia! I spotted two issues (unfortunately only after this PR has been merged):

1. The code of the deprecated `derive_params_exposure()` is still present in the function body. After calling `deprecate_warn()` it should simply pass its input arguments to the "new" `derive_param_exposure()`. Here's an example: https://github.com/Roche-GSK/admiral/blob/32c8b1704b3dc16e66a0ebaaab1c8880e6330667/R/derive_var_base.R#L132-L140
2. There should be a test case in `tests/testthat/deprecation.R` that checks whether a warning is issued when using the old `derive_params_exposure()`. Something like this: https://github.com/Roche-GSK/admiral/blob/32c8b1704b3dc16e66a0ebaaab1c8880e6330667/tests/testthat/test-deprecation.R#L216-L237

Is this something you could add and open a new PR? If not, I'm happy to take care of it.

**Comment by rossfarrugia** [comment]
i see @thomas-neitmann - i can update this no problem

**Comment by bundfussr** [comment]
Sorry, I missed those.

Could we add the two points to the "Deprecation" section in the "Programming Strategy"?

**Comment by thomas-neitmann** [comment]
We should, yes. Let's open a new ssue for that.

**Comment by bundfussr** [comment]
@rossfarrugia has added them to https://github.com/Roche-GSK/admiral/issues/765 👍 .

**Pull request merged**
