### PR TITLE
Add section on handling missing values

### LINKED ISSUE #531: Add `NA` Section to "Get Started" Vignette
A section regarding `NA` should be added to the "Get Started" vignette. It should state:
- All admiral functions expect that `NA` instead of `""` is used.
- admiral provides the `convert_blanks_to_na()` function to ensure that the input datasets fulfill the requirement.
- some examples of condition where you should take care, e.g., `DTYPE != "AVERAGE" | is.na(DTYPE)"` must be used instead of `DTYPE != "AVERAGE"`.

### PR DESCRIPTION
**Pull request by thomas-neitmann**
Close #531

### CODE REVIEW

**Comment by thomas-neitmann** [comment]
@bms63 @yangc71 Would be great if you could review this PR. If anything in the section I've added is unclear please let me know. That means I did a bad job 😉

**Review by yangc71 — COMMENTED** [review]
The Handling of Missing Values section is clear to me :). Should we also include reminders for functions such as min() max() that will return NA when NA is present if user doesn't specify `na.rm = T`?

**Comment by thomas-neitmann** [comment]
> Should we also include reminders for functions such as min() max() that will return NA when NA is present if user doesn't specify na.rm = T?

That's a great suggestions!

**Comment by thomas-neitmann** [comment]
@yangc71 I've incoprporated your suggestion. Feel free to approve this PR if it looks good to you 🙂

**Review by yangc71 — APPROVED** [review]

**Pull request merged**
